### ISSUE TITLE
update README about how to build from source code

### ISSUE THREAD

**Issue by missedone** [eriklupander/gotling#1]
hi @eriklupander 

build the project a have my shoe wet is the way how we evaluate the tool.
so it's better to document the build steps at least in README, even better is there is a kick start script to run, for example, Makefile or so.

anyway, i'm not sure how you build this project,

here is how i did with [gb](https://getgb.io)

```bash
# vendoring the dependencies
# if we use gb as well, i think you can commit the gb vendor manifest file so that others can easily restore the dependencies. 
gb vendor fetch gopkg.in/yaml.v2
gb vendor fetch github.com/NodePrime/jsonpath/cli/jsonpath
gb vendor fetch github.com/gorilla/websocket
gb vendor fetch github.com/tobyhede/go-underscore

# build
gb build

# now the executable binary should be under $PROJECT/bin
```

at last, thanks for sharing the idea and the project.

**Comment by eriklupander** [comment]
Hi,

thanks for you message. I have updated the README with some basic instructions about how to set it up using go get, GOPATH etc.

I'll look into gb as well. If I can get in running I'll update the README with that as well.

Thanks!

// Erik

**Comment by missedone** [comment]
hi,

i think it's better to introduce some vendoring tool so that all people can work with on the same dependency baseline, for example, gb creates $PROJECT/vendor/manifest, which looks like as below for gotling:
```
{
	"version": 0,
	"dependencies": [
		{
			"importpath": "github.com/NodePrime/jsonpath",
			"repository": "https://github.com/NodePrime/jsonpath",
			"revision": "84403ded544328c99be3472727667179eef23a91",
			"branch": "master"
		},
		{
			"importpath": "github.com/NodePrime/jsonpath/cli/jsonpath",
			"repository": "https://github.com/NodePrime/jsonpath",
			"revision": "84403ded544328c99be3472727667179eef23a91",
			"branch": "master",
			"path": "/cli/jsonpath"
		},
		{
			"importpath": "github.com/gorilla/websocket",
			"repository": "https://github.com/gorilla/websocket",
			"revision": "4935ba31a2adbfcd9e08b86d2657659afbf1af9a",
			"branch": "master"
		},
		{
			"importpath": "github.com/ogier/pflag",
			"repository": "https://github.com/ogier/pflag",
			"revision": "45c278ab3607870051a2ea9040bb85fcb8557481",
			"branch": "master"
		},
		{
			"importpath": "github.com/tobyhede/go-underscore",
			"repository": "https://github.com/tobyhede/go-underscore",
			"revision": "ea55fc9569918f099b1dfa785088434e5c53544d",
			"branch": "master"
		},
		{
			"importpath": "gopkg.in/yaml.v2",
			"repository": "https://gopkg.in/yaml.v2",
			"revision": "f7716cbe52baa25d2e9b0d0da546fcf909fc16b4",
			"branch": "v2"
		}
	]
}
```

you can commit this file to git (without the vendor source codes), then others can easily fetch the baseline via command: `gb vendor restore`.

and definitely there're several vendor tool (aka, dependency management tool) in golang community, gb is what i found easy for use and it's project based build tool so that won't conflict with my other projects.

**Comment by eriklupander** [comment]
Feel free to incorporate gb instructions to README.md and the manifest file.
