### ISSUE TITLE
Broken builds.

### ISSUE THREAD

**Issue by Nayar-sn** [eriklupander/gotling#11]
Build is broken as github.com/NodePrime/ is no longer there. It is more sensible to include the vendor package inside the main code base.

The project looks awesome - Please fix the build - so that I can try and play with this. 

Also, it is worthy of putting on godoc.org...

**Comment by eriklupander** [comment]
Thanks for the report. I'll see if I can replace NodePrime with something such as https://github.com/oliveagle/jsonpath

I'll also take the opportunity to convert this project to use go modules.

**Comment by eriklupander** [comment]
I've converted to project to use Go modules, Makefiles and changed the directory structure to follow https://github.com/golang-standards/project-layout better.

I've removed the JsonPath support, will try to find a NodePrime replacement ASAP.

**Comment by Nayar-sn** [comment]
Awesome. Thanks much

**Comment by Nayar-sn** [comment]
Awesome. Thanks much
