### ISSUE TITLE
[Question] Open to PRs?

### ISSUE THREAD

**Issue by retgits** [eriklupander/gotling#12]
Hi, I found this project while looking for a Go-based load testing tool. I totally like it and would love to contribute back some changes I made. I've added back the JSONPath handling and fixed a small bug in the `testdef.RANDOM` case in `passResultIntoSessionMap` .

**Comment by eriklupander** [comment]
Hi! Yes, I'll happily accept PRs, especially given that I don't have any plans on actively improving Gotling in the near future.

**Comment by retgits** [comment]
Awesome! I'll close this issue and open a PR
