### ISSUE TITLE
RFC - accept response by ignore the body

### ISSUE THREAD

**Issue by missedone** [eriklupander/gotling#2]
hi @eriklupander 

for now, gotling only support `accept: json`, for some case, i'd like to get the response, read the body but just simply ignore the data.
so, could you add support of this, for example, if we don't specify `accept` in the spec, then behavior as read body but ignore?

actually, i'd like to try to contribute PR if you think this is valid requirement.
thanks

**Comment by eriklupander** [comment]
I think having accept: json but not specifying a jsonpath will read the body without doing anything with it. Should be easy to modify to a better behaviour.

I added you as contributor. Feel free to push :)

**Comment by missedone** [comment]
right, as in PR #2, now `accept` is optional in test spec, which is default to 'text/html,application/json,application/xhtml+xml,application/xml,text/plain' if no value specified.
the json parse only happens when 'jsonpath' triggered for response.
