### ISSUE TITLE
RFC - accept xml content

### ISSUE THREAD

**Issue by missedone** [eriklupander/gotling#3]
hi @eriklupander 
for now, gotling only support `accept: json`, it'd be good if can support xml as well.
i saw there is golang [xmlpath](https://godoc.org/gopkg.in/xmlpath.v2) implement the xpath spec.

thanks

**Comment by eriklupander** [comment]
Sounds good, xmlpath (or perhaps gpath if there is a golang implementation) should be supported.

**Comment by eriklupander** [comment]
I have pushed a first attempt at using xmlpath. Seems to work but code needs to be cleaned up, unit-tested etc.

**Comment by missedone** [comment]
it'd better to mention in README that go-xmlpath does not support xml namespace yet https://github.com/go-xmlpath/xmlpath/pull/8
