### ISSUE TITLE
Example for session sensitive stress test

### ISSUE THREAD

**Issue by zanhsieh** [eriklupander/gotling#8]
Hi Erik,

I thanks for your wonderful contribution since have to fight with gatling session / scala for a long time, without anything I'm already familiar with go lang.

Just curious, since I have to deal with API stress test (most of them used for mobile devices), a lot of side-function have to be perform among requests. How do I do it in gotling?

For example, this is the code snippet I got previously on gatling:

```
...
  val scn_auto = scenario("android_auto")
      .exec(http("/api/register")
        .post("/api/register")
        .header("Accept","application/json, application/*+json")
        .header("Authorization", "%s".format(authorizationStr0))
        .header("Content-Type", "multipart/form-data;boundary=%s".format(sep0))
        .body(
          StringBody(
            session => body0
          )
        )
        .check(
          jsonPath("$.result").saveAs("result0")
        )
      )
      .exec(session => {
        result0 = session("result0").as[String]
        val decryptText: String = AES.decrypt(result0, todayPadding)
        val respJSON = JSON.parseFull(decryptText)
        client_id = respJSON
          .get
          .asInstanceOf[Map[String, Any]]("client_id")
          .asInstanceOf[String]
        client_secret_key = respJSON
          .get
          .asInstanceOf[Map[String, Any]]("client_secret_key")
          .asInstanceOf[String]
        println("client_id -> " + client_id)
        println("client_secret_key -> " + client_secret_key)
        session.set("sep1", genSep(r, 36)).set("client_id", client_id).set("client_secret_key", client_secret_key)
      })
      .exec(http("/api/login")
        .post("/api/login")
        .header("Accept","application/json, application/*+json")
        .header(
          "Authorization",
          session => {
            val theClientId = session("client_id").as[String]
            Base64.getEncoder.encodeToString(theClientId.getBytes("UTF-8"))
          })
        .header(
          "Content-Type",
          session => {
            val theSep = session("sep1").as[String]
            "multipart/form-data;boundary=%s".format(theSep)
          })
        .body(
          StringBody(
            session => {
              val theSep = session("sep1").as[String]
              val theClientSecretKey = session("client_secret_key").as[String]
              genBody(theSep, dataToCryptText(data1, theClientSecretKey))
            }
          )
        )
        .check(
          jsonPath("$.result").saveAs("result1")
        )
      )
...
```
AES.encrypt, AES.decrypt, genBody are my custom functions. Basic workflow is:

1. send my device id to server with today date as AES encrypt key + base64 encoded
1. base64 decoded + AES decrypt with today's date the response and save the private key issued
1. send my login id and pwd with AES encrypt the private key + base64 encoded and get response

How do I do the same thing in gotling?

**Comment by eriklupander** [comment]
Hi,

thanks for showing interest in Gotling!

I'm sorry to say, there is currently no way to add custom processing for transforming captured values to base64 or de/encrypting bodies.

I guess one of the strengths of Gatling is that you have the Scala APIs at your disposal for inlining stuff like the "dataToDecrypt" or base64 conversions.

In a gotling context, I guess one could add customizable processing steps on captured bodies or vars (or outgoing values from feeders), but that's not something I have thought of before. Not sure how it would be done in an elegant way either.

For now, I think you'll have to look at other options than Gotling for your needs. Good luck!

**Comment by zanhsieh** [comment]
Thanks. Close this issue for now.
